### ISSUE TITLE
ERROR: Invalid account: #0 for network: sepolia - private key too short, expected 32 bytes

### ISSUE THREAD

**Issue by ghost0913** [Metaschoolso/Hello-World-Smart-Contract#3]
When I excute 
```
npx hardhat compile
```
And I got an error:

```
Error HH8: There's one or more errors in your config file:

  * Invalid account: #0 for network: sepolia - private key too short, expected 32 bytes

To learn more about Hardhat's configuration, please go to https://hardhat.org/config/  
```

This is my hardhat.config.js
```
require("dotenv").config();
require("@nomiclabs/hardhat-ethers");
const PRIVATE_KEY = process.env.PRIVATE_KEY;

module.exports = {
  solidity: "0.8.19",
  defaultNetwork: "sepolia",
  networks: {
    hardhat: {},
    sepolia: {
      url: "https://eth-sepolia.g.alchemy.com/v2/xxxxxxxxxxx",
      accounts: ['0x${PRIVATE_KEY}'],

    },
  },
};
```
I have patsed the private key rather than the public key, and put '0x' as the prefix at the PRIVATE_KEY. But I still failed .

**Comment by ghost0913** [comment]
And I found if put 'account' rather than 'accounts',  and delete '0x', like this:
```
    sepolia: {
      url: "https://eth-sepolia.g.alchemy.com/v2/xxxxxxxxxxx",
      account: ['${PRIVATE_KEY}'],
    },

```
and execute ``` npx hardhat compile ```, it works!  But it will failed when execute 
```
npx hardhat run scripts/deploy.js --network sepolia
```
There is an error:
```
Deploying Contract...
**TypeError: Cannot read properties of null (reading 'sendTransaction')**
    at ContractFactory.<anonymous> (C:\Users\YayingLuo\Desktop\Hello-World\node_modules\@ethersproject\contracts\src.ts\index.ts:1247:38)
    at step (C:\Users\YayingLuo\Desktop\Hello-World\node_modules\@ethersproject\contracts\lib\index.js:48:23)
    at Object.next (C:\Users\YayingLuo\Desktop\Hello-World\node_modules\@ethersproject\contracts\lib\index.js:29:53)    
    at fulfilled (C:\Users\YayingLuo\Desktop\Hello-World\node_modules\@ethersproject\contracts\lib\index.js:20:58)      
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
I have tried many times. I don't know why and how to solve it. Hoping for a solution. Thanks.
